# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/SDU/4th Semester/Semester Project/mspro4/Led Panel Driver V2/Led Panel Driver V2.srcs/sources_1/ip/audio_block_mem/audio_block_mem.xci
# IP: The module: 'audio_block_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SDU/4th Semester/Semester Project/mspro4/Led Panel Driver V2/Led Panel Driver V2.srcs/sources_1/ip/audio_block_mem/audio_block_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_block_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/SDU/4th Semester/Semester Project/mspro4/Led Panel Driver V2/Led Panel Driver V2.srcs/sources_1/ip/audio_block_mem/audio_block_mem.xci
# IP: The module: 'audio_block_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SDU/4th Semester/Semester Project/mspro4/Led Panel Driver V2/Led Panel Driver V2.srcs/sources_1/ip/audio_block_mem/audio_block_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_block_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
